import { writeFileSync } from "fs-extra"
import {
    AZURE_CLOUD_CONSTANTS,
    AZURE_EMISSIONS_FACTORS_METRIC_TON_PER_KWH,
} from "../packages/azure"

import {
    CACHE_MEMORY_GB,
    COMPUTE_USAGE_UNITS,
    CONTAINER_REGISTRY_STORAGE_GB,
    HDD_MANAGED_DISKS_STORAGE_GB,
    MEMORY_USAGE_TYPES,
    MEMORY_USAGE_UNITS,
    NETWORKING_USAGE_TYPES,
    NETWORKING_USAGE_UNITS,
    SSD_MANAGED_DISKS_STORAGE_GB,
    STORAGE_USAGE_TYPES,
    STORAGE_USAGE_UNITS,
    UNKNOWN_SERVICES,
    UNKNOWN_USAGE_TYPES,
    UNSUPPORTED_USAGE_TYPES,
} from '../packages/azure/src/lib/ConsumptionTypes'

import {
    GPU_VIRTUAL_MACHINE_TYPE_PROCESSOR_MAPPING,
    GPU_VIRTUAL_MACHINE_TYPES,
    INSTANCE_TYPE_COMPUTE_PROCESSOR_MAPPING,
    VIRTUAL_MACHINE_TYPE_CONSTRAINED_VCPU_CAPABLE_MAPPING,
    VIRTUAL_MACHINE_TYPE_SERIES_MAPPING,
    VIRTUAL_MACHINE_TYPE_VCPU_MEMORY_MAPPING,
} from "../packages/azure/src/lib/VirtualMachineTypes"

const keys = [
    "SSDCOEFFICIENT",
    "HDDCOEFFICIENT",
    "MEMORY_AVG",
    "MEMORY_BY_COMPUTE_PROCESSOR",
    "MIN_WATTS_AVG",
    "MIN_WATTS_BY_COMPUTE_PROCESSOR",
    "MAX_WATTS_AVG",
    "MAX_WATTS_BY_COMPUTE_PROCESSOR",
    "NETWORKING_COEFFICIENT",
    "MEMORY_COEFFICIENT",
    "PUE_AVG",
    "AVG_CPU_UTILIZATION_2020",
    "REPLICATION_FACTORS",
    "SERVER_EXPECTED_LIFESPAN",
]

const config = {
    constants: {
        EMISSIONS_FACTORS_METRIC_TON_PER_KWH: AZURE_EMISSIONS_FACTORS_METRIC_TON_PER_KWH,
        INSTANCE_TYPE_COMPUTE_PROCESSOR_MAPPING,
        ...Object.fromEntries(keys.map(key => [key, AZURE_CLOUD_CONSTANTS[key]])),
    },
    parameters: {
        CACHE_MEMORY_GB,
        CONTAINER_REGISTRY_STORAGE_GB,
        HDD_MANAGED_DISKS_STORAGE_GB,
        MEMORY_USAGE_TYPES,
        NETWORKING_USAGE_TYPES,
        SSD_MANAGED_DISKS_STORAGE_GB,
        STORAGE_USAGE_TYPES,
        UNKNOWN_SERVICES,
        UNKNOWN_USAGE_TYPES,
        UNSUPPORTED_USAGE_TYPES,
        NETWORKING_USAGE_UNITS: Object.values(NETWORKING_USAGE_UNITS),
        MEMORY_USAGE_UNITS: Object.values(MEMORY_USAGE_UNITS),
        COMPUTE_USAGE_UNITS: Object.values(COMPUTE_USAGE_UNITS),
        STORAGE_USAGE_UNITS: Object.values(STORAGE_USAGE_UNITS),
        GPU_VIRTUAL_MACHINE_TYPE_PROCESSOR_MAPPING,
        GPU_VIRTUAL_MACHINE_TYPES,
        VIRTUAL_MACHINE_TYPE_VCPU_MEMORY_MAPPING,
        VIRTUAL_MACHINE_TYPE_CONSTRAINED_VCPU_CAPABLE_MAPPING,
        VIRTUAL_MACHINE_TYPE_SERIES_MAPPING,
    },
}

config.parameters["CACHE_MEMORY_GB"]["C0"] = 0.25

writeFileSync("cycloid/out/azure_config.json", JSON.stringify(config))

// NODE_OPTIONS="--no-warnings" npx ts-node -T cycloid/azure_config.ts  